# Quick Look plugins to install.
# Values to be Homebrew Cask package names.
# GitHub lists quite a few (ensure that they are available via Cask):
# https://github.com/search?utf8=%E2%9C%93&q=Quick+Look+plugin&type=
quick_look_plugins_list:
  - qlcolorcode
  - qlmarkdown
  - qlstephen
  - quicklook-json
  - webpquicklook
