---

- name: Install Transmission
  homebrew_cask: name=transmission state=present
  notify: brew cask cleanup

- name: Ensure location for incomplete downloads exists
  file:
    path: /Users/{{ ansible_env.USER }}/Downloads/Torrents/Incomplete
    state: directory
    follow: yes

- name: Keep incomplete downloads
  osx_defaults:
    domain: org.m0k.transmission
    key: UseIncompleteDownloadFolder
    type: bool
    value: true
  notify: killall Transmission

- name: Set path for incomplete downloads
  osx_defaults:
    domain: org.m0k.transmission
    key: IncompleteDownloadFolder
    type: string
    value: "${HOME}/Downloads/Torrents/Incomplete"
  notify: killall Transmission

- name: "{{ item.name }}"
  osx_defaults:
    domain: org.m0k.transmission
    key: "{{ item.key }}"
    type: bool
    value: "{{ item.value }}"
  with_items:
    - { name: "Don't prompt for confirmation before downloading", key: "DownloadAsk", value: "false"}
    - { name: "Trash original torrent files", key: "DeleteOriginalTorrent", value: "true"}
    - { name: "Hide the donate message", key: "WarningDonate", value: "false"}
    - { name: "Hide the legal disclaimer", key: "WarningLegal", value: "false"}
  notify: killall Transmission
